echo "ENV=$ENV" > .env
echo "POSTGRES_HOST=$POSTGRES_HOST" >> .env
echo "POSTGRES_PORT=$POSTGRES_PORT" >> .env
echo "POSTGRES_DB=$POSTGRES_DB" >> .env
echo "POSTGRES_USERNAME=$POSTGRES_USERNAME" >> .env
echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> .env
echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> .env
echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> .env
echo "AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION" >> .env
echo "AWS_REGION=$AWS_REGION" >> .env
echo "AWS_PROFILE=$AWS_PROFILE" >> .env
echo "AWS_BUCKET=$AWS_BUCKET" >> .env
echo "RDS_DIALECT=$RDS_DIALECT" >> .env
echo "RDS_INSTANCE=$RDS_INSTANCE" >> .env
echo "EB_APP_NAME=$EB_APP_NAME" >> .env
echo "EB_ENVIRONMENT=$EB_ENVIRONMENT" >> .env
echo "URL=$URL" >> .env
echo "JWT_SECRET=$JWT_SECRET" >> .env


